import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{margin: "0", padding: "0", boxSizing: "border-box",display:"flex",flexDirection:"column",minHeight:"100vh"}}>
        <header style={{ background: "aquamarine",width:"100%",height:"100px" }}>
          <Link href={"/"}>Home</Link>
          <Link href={"/products"} style={{marginLeft:"10px"}}>Products</Link>
        </header>
        <main style={{flex:"1 0 auto"}}>
                  {children}
        </main>
      <footer style={{ background: "aquamarine",width:"100%",height:"100px" }}></footer>
      </body>
    </html>
  )
}
