export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{display:"flex",flexDirection:"column",minHeight:"100vh"}}>
        <header style={{ background: "aquamarine",width:"100%",height:"100px" }}></header>
        <main style={{flex:"1 0 auto"}}>
                  {children}
        </main>
      <footer style={{ background: "aquamarine",width:"100%",height:"100px" }}></footer>
      </body>
    </html>
  )
}
