import type { Metadata } from "next";
import "./globals.css";
import Header from "@/Components/Header";
import { ClerkProvider } from "@clerk/nextjs";


export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body style={{ margin: "0", padding: "0", boxSizing: "border-box", display: "flex", flexDirection: "column", minHeight: "100vh" }}>
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}