import "./global.css"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
                <body style={{ margin: "0", padding: "0", boxSizing: "border-box", display: "flex", flexDirection: "column", minHeight: "100vh" }}>
                    {children}
                </body>
        </html>
    )
}
