import Link from "next/link"
import { Metadata } from "next"
import { ErrorWrapper } from "../error-wrapper"

export const metadata: Metadata = {
  title: {
    default: "Next.js practice",
    template: "%s | Next.js practice",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ display: "flex", flexDirection: "column", minHeight: "100vh" }}>
        <header style={{ background: "aqua", width: "100%", height: "100px" }}>
          <Link href={"/"}>Home</Link>
        </header>
        <main style={{ flex: "1 0 auto" }}>
          <ErrorWrapper>
            {children}
          </ErrorWrapper>
        </main>
        <footer style={{ background: "aqua", width: "100%", height: "100px" }}></footer>
      </body>
    </html>
  )
}
